trigger:
  branches:
    include:
      - main
  paths:
    include:
      - deploy/main.bicep

pool:
  vmImage: 'ubuntu-latest'

parameters:
  - name: environment
    displayName: 'Environment'
    type: string
    default: 'dev'
    values:
      - dev
      - test
      - prod

variables:
  - name: azureSubscription
    value: 'YOUR_AZURE_SERVICE_CONNECTION_NAME'
  - name: resourceGroupName
    value: 'rg-tob-accounts-${{ parameters.environment }}'
  - name: location
    value: 'East US'

stages:
  - stage: Validate
    displayName: 'Validate Bicep Template'
    jobs:
      - job: ValidateBicep
        displayName: 'Validate Bicep'
        steps:
          - task: AzureCLI@2
            displayName: 'Validate Bicep Template'
            inputs:
              azureSubscription: $(azureSubscription)
              scriptType: 'bash'
              scriptLocation: 'inlineScript'
              inlineScript: |
                az bicep build --file $(Build.SourcesDirectory)/deploy/main.bicep
                echo "Bicep validation successful"

  - stage: Deploy
    displayName: 'Deploy Infrastructure'
    dependsOn: Validate
    condition: succeeded()
    jobs:
      - deployment: DeployInfrastructure
        displayName: 'Deploy to Azure'
        environment: ${{ parameters.environment }}
        strategy:
          runOnce:
            deploy:
              steps:
                - checkout: self

                - task: AzureCLI@2
                  displayName: 'Create Resource Group'
                  inputs:
                    azureSubscription: $(azureSubscription)
                    scriptType: 'bash'
                    scriptLocation: 'inlineScript'
                    inlineScript: |
                      az group create \
                        --name $(resourceGroupName) \
                        --location "$(location)"

                - task: AzureResourceManagerTemplateDeployment@3
                  displayName: 'Deploy Bicep Template'
                  inputs:
                    deploymentScope: 'Resource Group'
                    azureResourceManagerConnection: $(azureSubscription)
                    subscriptionId: '$(subscriptionId)'
                    action: 'Create Or Update Resource Group'
                    resourceGroupName: $(resourceGroupName)
                    location: $(location)
                    templateLocation: 'Linked artifact'
                    csmFile: '$(Build.SourcesDirectory)/deploy/main.bicep'
                    overrideParameters: >
                      -environmentName "${{ parameters.environment }}"
                      -location "$(location)"
                      -appServicePlanName "$(appServicePlanName)"
                      -sqlServerName "$(sqlServerName)"
                      -keyVaultName "$(keyVaultName)"
                      -applicationName "tob-accounts-api"
                      -entraIdTenantId "$(entraIdTenantId)"
                      -entraIdClientId "$(entraIdClientId)"
                      -entraIdAudience "$(entraIdAudience)"
                      -corsAllowedOrigins "$(corsAllowedOrigins)"
                      -otlpEndpoint "$(otlpEndpoint)"
                      -enableTracing true
                      -enableMetrics true
                      -enableLogging true
                    deploymentMode: 'Incremental'
                    deploymentOutputs: 'deploymentOutputs'

                - task: PowerShell@2
                  displayName: 'Parse Deployment Outputs'
                  inputs:
                    targetType: 'inline'
                    script: |
                      $outputs = ConvertFrom-Json '$(deploymentOutputs)'
                      foreach ($output in $outputs.PSObject.Properties) {
                        Write-Host "##vso[task.setvariable variable=$($output.Name);isOutput=true]$($output.Value.value)"
                        Write-Host "$($output.Name): $($output.Value.value)"
                      }
